CREATE USER placeholder WITH PASSWORD 'placeholder';
GRANT ALL PRIVILEGES ON DATABASE "placeholder" to placeholder;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO placeholder;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO placeholder;
